// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  dividing_line: defineAsyncComponent(() => import("./DividingLine/index.vue")),
  headline: defineAsyncComponent(() => import("./Headline/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  image_slider: defineAsyncComponent(() => import("./ImageSlider/index.vue")),
  recommendations: defineAsyncComponent(
    () => import("./Recommendations/index.vue"),
  ),
  spacer: defineAsyncComponent(() => import("./Spacer/index.vue")),
  text: defineAsyncComponent(() => import("./Copy/index.vue")),
});
